// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import 'dotenv/config'
// import { defineConfig } from 'prisma/config'

// export default defineConfig({
//   schema: 'prisma/schema.prisma',
//   migrations: {
//     path: 'prisma/migrations',
//   },
//   datasource: {
//     url: process.env.DATABASE_URL,
//   },
// })

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: { path: "prisma/migrations" },
  datasource: {
    url: env("DIRECT_URL"),
  },
});


//--------------------------------------------------------------
//--------------------------------------------------------------
//--------------------------------------------------------------
// The different version of config are below, had to trial and error to get it working
// The above is the final version that works


//url: process.env["DATABASE_URL"],
// url: env('DATABASE_URL'),

/*

schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },

*/